# Docker Compose for CoachManager System - Local Development
# Modern Education Platform for Classes 6-10

version: '3.8'

services:
  # PostgreSQL Database for Local Development
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: coachmanager
      POSTGRES_USER: rahman
      POSTGRES_PASSWORD: rahman
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./coachdb_2025-09-08.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rahman -d coachmanager"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application
  app:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://chemistry_user:${POSTGRES_PASSWORD:-secure_password_123}@postgres:5432/chemistry_ict_care
      SESSION_SECRET: ${SESSION_SECRET:-generate_a_secure_session_secret}
      BULKSMS_API_KEY: ${BULKSMS_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates here
    profiles:
      - nginx  # Only start with: docker-compose --profile nginx up

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: chemistry-ict-network